/**
 * pinky quotes, for science
 */
module.exports = [
  "I think so, %s, but if we covered the world in salad dressing wouldn't the aspargus feel left out?",
  "I think so, %s, but if they called them 'Sad Meals', kids wouldn't buy them!",
  "I think so, %s, but me and Pippi Longstocking -- I mean, what would the children look like?",
  "Well, I think so, %s, but I can't memorize a whole opera in Yiddish.",
  "Well, I think so %s but where do you stick the feather and call it macaroni?",
  "Well, I think so, %s, but it's a miracle that this one grew back.",
  "I think so, %s, but isn't that why they invented tube socks?",
  "Oooh, I think so %s, but I think I'd rather eat the Macarena.",
  "Well, I think so %s, but Kevin Costner with an English accent?",
  "Well, I think so, %s, but if Jimmy cracks corn, and no one cares, why does he keep doing it?",
  "I think so, %s, but how will we get a pair of Abe Vigoda's pants?",
  "I think so, %s, but Pete Rose? I mean, can we trust him?",
  "I think so, %s, but isn't a cucumber that small called a gherkin?",
  "I think so, Larry, and um, %s, but how can we get seven dwarves to shave their legs?",
  "I think so, %s, but calling it pu-pu platter? Huh, what were they thinking?",
  "I think so, %s, but how will we get the Spice Girls into the paella?",
  "I think so, %s, but if we give peas a chance, won't the lima beans feel left out?",
  "I think so, %s, but what kind of rides do they have in Fabioland?",
  "I think so, %s, but can the Gummi Worms really live in peace with the Marshmallow Chicks?",
  "I think so, %s, but three round meals a day wouldn't be as hard to swallow.",
  "I think so, %s, but if the plural of mouse is mice, wouldn't the plural of spouse be spice?",
  "Umm, I think so, %s, but three men in a tub? Ooh, that's unsanitary!",
  "Yes, but why does the chicken cross the road, huh, if not for love? I do not know.",
  "Yes %s, but if our knees bent the other way, how would we ride a bicycle?",
  "Wuh, I think so, %s, but how will we get three pink flamingos into one pair of Capri pants?",
  "I think so, %s, but why would anyone want to see Snow White and the Seven Samurai?",
  "I think so, %s, but I find scratching just makes it worse.",
  "I think so, %s, but why would anyone want a depressed tongue?",
  "I think so, %s, but wouldn't his movies be more suitable for children if he was named Jean-Claude van Darn?",
  "Wuh, I think so, %s, but will they let the Cranberry Duchess stay in the Lincoln Bedroom?",
  "I think so, %s, but why does a forklift have to be so big if all it does is lift forks?",
  "I think so, %s, but if it was only supposed to be a three hour tour, why did the Howells bring all their money?",
  "I think so, %s, but if we have nothing to fear but fear itself, why does Eleanor Roosevelt wear that spooky mask?",
  "Um, I think so, %s, but a show about two talking lab mice? Hoo! It'll never get on the air.",
  "I think so, %s. But if I put on two tutu's, would I really be wearing a four-by-four?",
  "I think so, %s, but wouldn't mustard make it sting?",
  "I think so, %s, but can you use the word 'asphalt' in polite society?",
  "I think so, Mr. %s, but if the sun'll come out tomorrow, what's it doing right now?",
  "Um, I think so, %s, but I hear Hillary is the jealous type.",
  "Uh, I think so, %s--but after eating newspaper all day, do I really need the extra fiber?",
  "I think so, %s. But will anyone other than Eskimos buy blubber-flavored chewing gum?",
  "I think so, %s. But would the villains really have gotten away with it, if it weren't for those pesky kids and their dog?",
  "Uh, I think so %s, but how are we gonna teach a goat to dance with flippers on?",
  "I think so, %s, but a codpiece made from a real fish would get smelly after a while, wouldn't it?",
  "I think... so, %s... *gag* ...but I didn't know Annette used peanut butter in that way.",
  "Whuh... I think so, %s. But this time I get to play the dishwasher repairman!",
  "Whuh... I think so, %s, but... but if Charlton Heston doesn't eat Soylent Green, what will he eat?",
  "I think so, %s, but wouldn't an itsy-bitsy, teeny-weenie, yellow polka-dot one-piece be better suited for my figure?",
  "I think so, %s! We'll dress up like biker dudes and infiltrate the 'Hades Ladies'. Then we'll convince them to hold a meeting inside the corn palace. Narf! The resulting carbon-monoxide buildup will allow you to complete your energy-making device and shortly after, you will rule the world!",
  "I think so, %s! You draw the bath and I'll fetch the alka-seltzers and candles!",
  "I think so, %s! But ruby-studded stockings would be mighty uncomfortable wouldn't they?",
  "I think so, %s, but if I have my portrait drawn, will we have time to make it to the lifeboats?",
  "I think so, %s! But is Chippendale's ready for 'The Full Pinky?'",
  "I think so, %s! But do I have what it take to be the 'Lord of the Dance'?",
  "I think so, %s, but nose rings are kinda passe by now.",
  "I think so, %s, but where are we going to get a trained octopus at this time of night?",
  "I think so, %s, but I didn't know 90210 was a real zip code! Will Tori be there?",
  "Narf! I think so, %s, but what if the Telechubbies don't fight fair?",
  "I think so, %s. But if Pinocchio were carved out of bacon it wouldn't be the same story, would it?",
  "I think so, %s. But suppose we do the hokey pokey and turn ourselves around, is that what it's really all about?",
  "I think so, %s, but how are we going to get the bacon flavoring into the pencils?",
  "I think so, %s, but she'd never leave Mickey."
];